/**
 * The README's screenshot, taken from the running application rather than from a window somebody
 * had open once.
 *
 * A hand-taken picture goes stale exactly the way the text around it does, and nothing says when:
 * the panel gains a column, the shot keeps the old one, and the first person to notice is a
 * visitor who thinks the repository was abandoned. This one is regenerated by a command, so the
 * cost of being current is running it.
 *
 * It is Playwright's runner rather than a script driving the library, because the runner already
 * owns everything the shot has to be pinned to: one origin behind the same `/api` proxy the tests
 * and production use, a production build rather than the dev server, a fixed viewport and scale.
 * A script of my own would be a second, quieter copy of playwright.config.ts.
 *
 * Its own config, not a project inside that one, so `npm run test:e2e` and CI never take a
 * picture. The capture needs the base world with its own data in it; a check that fails the build
 * over a screenshot would be a cosmetic problem stopping a release.
 *
 * Usage:  npm --prefix frontend run capture
 */

import { defineConfig, devices } from '@playwright/test'

/** Not 4173. The e2e preview lives there, and reusing whatever answers on a port is how a shot of
 *  last week's build ends up in the README looking like this week's. */
const port = Number(process.env['CAPTURE_PORT'] ?? 4174)
const baseURL = `http://127.0.0.1:${port}`

export default defineConfig({
  testDir: './capture',
  testMatch: '**/*.capture.ts',

  // No retries and one worker: a capture that failed produced no picture, and running it again is
  // a keystroke. Parallelism would only put two browsers in front of the same login throttle.
  workers: 1,
  retries: 0,
  timeout: 120_000,
  expect: { timeout: 15_000 },
  reporter: [['list']],

  use: { baseURL },

  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],

        // AFTER the device, not beside it: a project's `use` beats the top-level one, so a
        // viewport declared up there is silently replaced by the device's 1280x720 at scale 1 —
        // which is a shot of a smaller window than the layout was drawn for.
        //
        // 1440 is that width. The height is chosen so that the filters, the rows and the pager
        // land in one viewport, which is what makes this a picture of a screen rather than a
        // full-page strip of one; the capture asserts the pager is inside it.
        viewport: { width: 1440, height: 1260 },

        // Retina, because the README is read on the machines this was built on and 13px type in
        // a 1x PNG is legible on none of them.
        deviceScaleFactor: 2,
      },
    },
  ],

  webServer: {
    // The production build, for the same reason the e2e run uses it: that is what is deployed,
    // and a picture of the dev server is a picture of something nobody visits.
    command: `npm run build && npm run preview -- --host 127.0.0.1 --port ${port} --strictPort`,
    url: baseURL,
    // Never reused. If something already answers here the capture stops and says so, rather than
    // photographing it — a stale screenshot is the one failure this whole file exists to prevent.
    reuseExistingServer: false,
    timeout: 120_000,
    stdout: 'pipe',
    stderr: 'pipe',
  },
})
