"""What autogenerate is allowed to see.

The application owns one schema, `admin`, and shares the database with whatever else lives in
`public`. `include_schemas=True` is what lets alembic see `admin` at all, and it is also what
makes alembic reflect everything else; the filter is the only thing standing between that and an
autogenerated revision proposing `DROP TABLE` for tables this project did not write.

A filter of this shape fails silently when it is wrong — it goes on returning an answer, just the
wrong one, and nobody finds out until a revision is generated and read carelessly. So the case it
exists for is asserted directly: a real table, created in `public`, reflected the way alembic
reflects it, and refused.
"""

from typing import Final

from sqlalchemy import Connection, MetaData, text
from sqlalchemy.ext.asyncio import AsyncConnection

from app.models import SCHEMA, Base
from app.schema_filter import include_object

# Created inside the test's transaction and rolled back with it.
_PUBLIC_TABLE: Final = "a_table_this_project_does_not_own"

_USERS: Final = Base.metadata.tables[f"{SCHEMA}.users"]
_REFRESH_TOKENS: Final = Base.metadata.tables[f"{SCHEMA}.refresh_tokens"]


async def test_a_table_in_public_is_excluded(connection: AsyncConnection) -> None:
    """The case the filter exists for, and the one a comparison against "public" would miss.

    Alembic and SQLAlchemy name the default schema `None`, never the string "public", so a
    predicate written as `schema != "public"` matches nothing and admits every table in it. The
    reflection below is what makes that concrete rather than remembered.
    """
    await connection.execute(text(f"CREATE TABLE public.{_PUBLIC_TABLE} (id integer primary key)"))
    metadata = MetaData()
    await connection.run_sync(_reflect, metadata)
    table = metadata.tables[_PUBLIC_TABLE]

    assert table.schema is None
    assert include_object(table, table.name, "table", True, None) is False
    assert include_object(table.c.id, "id", "column", True, None) is False


def test_a_table_in_the_admin_schema_is_included() -> None:
    """The other half: a filter that excluded everything would also never propose a DROP."""
    assert include_object(_USERS, "users", "table", False, None) is True
    assert include_object(_USERS.c.email, "email", "column", False, None) is True


def test_a_constraint_or_index_is_judged_by_the_table_it_belongs_to() -> None:
    """Alembic asks about columns, indexes and constraints too, and none of them carry a schema of
    their own. Answering `None` for those would exclude the application's own objects and leave
    autogenerate proposing to drop them."""
    index = next(iter(_REFRESH_TOKENS.indexes))
    constraint = _USERS.primary_key

    assert include_object(index, index.name, "index", False, None) is True
    assert include_object(constraint, constraint.name, "primary_key", False, None) is True


def _reflect(sync_connection: Connection, metadata: MetaData) -> None:
    """Reflect the one table above, the way alembic reflects the default schema: by not naming
    one. `run_sync` because reflection is inspection, and the inspector is synchronous."""
    metadata.reflect(bind=sync_connection, only=[_PUBLIC_TABLE])
