/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an email and password for an access token
         * @description Authenticate a person and start a refresh-token family for the device they used.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke this device's refresh-token family
         * @description Always 204. A caller who is already logged out has got what they asked for.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Describe the current session
         * @description Report the user, their role and what that role grants, as the database says right now.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh cookie and mint a new access token
         * @description Consume the presented refresh token and issue its successor in the same family.
         */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report the service version and whether the database answers
         * @description Answer 200 when Postgres responds and 503 when it does not.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plans
         * @description The whole catalogue, in the order the table's plan filter should offer it.
         *
         *     The filter needs every plan, not the ones that happen to appear on the page being looked at —
         *     a filter offering four of five because the fifth is on page two is a filter that hides people.
         *     The order is the catalogue's own, which is the duration ladder, so it reads shortest to
         *     longest rather than alphabetically.
         */
        get: operations["list_plans_api_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscribers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One page of subscribers, filtered and sorted */
        get: operations["list_page_api_subscribers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscribers/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One subscriber: the subscription, its plan, its promo code and its referrer */
        get: operations["read_one_api_subscribers__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscribers/{user_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One page of what has happened to this subscriber, newest first */
        get: operations["read_events_api_subscribers__user_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the operators of this panel
         * @description One page of users, under an ordering the client can page through safely.
         */
        get: operations["list_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorBody
         * @description The contents of the envelope.
         */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
        };
        /**
         * ErrorCode
         * @description The closed catalogue of machine-readable failures.
         *
         *     Closed is the point: the frontend has a switch over these values, and a code invented at a
         *     call site is a code that falls through it.
         * @enum {string}
         */
        ErrorCode: "INVALID_CREDENTIALS" | "NOT_AUTHENTICATED" | "TOKEN_EXPIRED" | "USER_INACTIVE" | "PERMISSION_DENIED" | "REFRESH_TOKEN_INVALID" | "REFRESH_TOKEN_REUSED" | "RATE_LIMITED" | "VALIDATION_ERROR" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "INTERNAL_ERROR";
        /**
         * ErrorEnvelope
         * @description The body of every non-2xx response this service produces.
         *
         *     Routes declare it in `responses=` so the published schema says so as well.
         */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * HealthResponse
         * @description GET /api/health.
         */
        HealthResponse: {
            /** Commit */
            commit: string;
            /** Db */
            db: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            world: components["schemas"]["WorldHealth"];
        };
        /**
         * LoginRequest
         * @description POST /api/auth/login.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MeResponse
         * @description GET /api/auth/me.
         */
        MeResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "user" | "demo";
            /** Permissions */
            permissions: string[];
            role: components["schemas"]["RoleSummary"];
            user: components["schemas"]["UserProfile"];
            /** Worldid */
            worldId?: string | null;
        };
        /**
         * PlanSummary
         * @description The plan a subscription is on, as the card shows it.
         */
        PlanSummary: {
            /** Currency */
            currency: string;
            /** Gracedays */
            graceDays: number;
            /** Id */
            id: string;
            /** Periodcount */
            periodCount: number;
            /**
             * Periodunit
             * @enum {string}
             */
            periodUnit: "days" | "months";
            /** Price */
            price: number;
            /** Trialdays */
            trialDays: number;
        };
        /**
         * RoleSummary
         * @description A role as the panel displays it. `id` stays inside the process.
         */
        RoleSummary: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /**
         * SubscriberDetail
         * @description GET /api/subscribers/{id}: the subscription, its plan, its promo code and its referrer.
         */
        SubscriberDetail: {
            plan: components["schemas"]["PlanSummary"];
            /** Promocode */
            promoCode?: string | null;
            /** Referralprogramid */
            referralProgramId?: string | null;
            /** Referrerid */
            referrerId?: string | null;
            subscriber: components["schemas"]["SubscriberSummary"];
        };
        /**
         * SubscriberEvent
         * @description One entry of a subscriber's feed.
         *
         *     `payload` is whatever the event carried beyond the three columns that index it, and its keys
         *     differ per type — `payment.recorded` has an amount, `subscription.expired` has a reason. It is
         *     typed as an open object on purpose: naming a union of fourteen payload shapes in the schema
         *     would make every new event in a later engine a breaking change to this API.
         */
        SubscriberEvent: {
            /** Id */
            id: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Type */
            type: string;
        };
        /**
         * SubscriberEventPage
         * @description GET /api/subscribers/{id}/events, in the shape every collection here answers with.
         */
        SubscriberEventPage: {
            /** Items */
            items: components["schemas"]["SubscriberEvent"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /**
         * SubscriberPage
         * @description GET /api/subscribers. The shape the specification fixes: items, total, page, pageSize.
         */
        SubscriberPage: {
            /** Items */
            items: components["schemas"]["SubscriberSummary"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /**
         * SubscriberSummary
         * @description One row of the subscriber table.
         *
         *     The date fields are a discriminated view rather than a bag of optionals: `trialEndsAt` is set
         *     only in TRIAL, `graceEndsAt` only in GRACE. The frontend's tagged union is built on that, so a
         *     field that is present in a state it does not belong to would be a type that lies.
         *
         *     `accessUntil` sits alongside them rather than replacing them. It is the one of the three that
         *     is true in the state the row is in, which is what a table with a single date column has to
         *     show; the three stay because they are different questions and the subscriber card asks all of
         *     them separately.
         */
        SubscriberSummary: {
            /** Accessuntil */
            accessUntil?: string | null;
            /** Displayname */
            displayName: string;
            /** Expiresat */
            expiresAt?: string | null;
            /** Graceendsat */
            graceEndsAt?: string | null;
            /** Lastactiveat */
            lastActiveAt?: string | null;
            /** Planid */
            planId: string;
            /** Promocode */
            promoCode?: string | null;
            /** Referrerid */
            referrerId?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "trial" | "active" | "grace" | "expired" | "cancelled";
            /** Trialendsat */
            trialEndsAt?: string | null;
            /** Userid */
            userId: string;
        };
        /**
         * TokenResponse
         * @description The answer to POST /api/auth/login and POST /api/auth/refresh.
         *
         *     Both mint an access token under identical terms, and the refresh token itself is never in a
         *     body — it is in the cookie, where script cannot read it.
         */
        TokenResponse: {
            /** Accesstoken */
            accessToken: string;
            /** Expiresin */
            expiresIn: number;
        };
        /**
         * UserListResponse
         * @description GET /api/users.
         */
        UserListResponse: {
            /** Items */
            items: components["schemas"]["UserSummary"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /**
         * UserProfile
         * @description The subject of the session, as GET /api/auth/me reports it.
         */
        UserProfile: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isactive */
            isActive: boolean;
            /** Lastloginat */
            lastLoginAt: string | null;
        };
        /**
         * UserSummary
         * @description A row of GET /api/users: the profile, plus the role it was granted.
         */
        UserSummary: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isactive */
            isActive: boolean;
            /** Lastloginat */
            lastLoginAt: string | null;
            role: components["schemas"]["RoleSummary"];
        };
        /**
         * WorldHealth
         * @description Whether the demonstration has a world behind it.
         *
         *     Reported beside the database rather than folded into `status`, because the two failures are
         *     not the same kind. A database that does not answer means the panel cannot serve; a world that
         *     failed to seed means the shop window is empty while signing in, permissions and every
         *     operator screen keep working. Answering 503 for the second would make a deploy roll itself
         *     back over a cosmetic problem.
         */
        WorldHealth: {
            /** Events */
            events: number;
            /** Seeded */
            seeded: boolean;
            /** Subscribers */
            subscribers: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description The database did not answer. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_plans_api_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_page_api_subscribers_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                sort?: string;
                state?: ("trial" | "active" | "grace" | "expired" | "cancelled")[];
                planId?: string[];
                cohort?: ("quiet" | "trial-ending" | "cancelled-still-active") | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriberPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    read_one_api_subscribers__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriberDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    read_events_api_subscribers__user_id__events_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriberEventPage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
