"""What alembic's autogenerate is allowed to look at.

This lives in the application package rather than in `alembic/env.py` because env.py runs the
migrations at import — that is alembic's contract with it — so nothing defined inside it can be
imported by a test. The filter below is the one piece worth testing on its own: it is what stops
autogenerate from proposing `DROP TABLE` for everything in `public`, and a filter that silently
never matches looks exactly like a filter that works.
"""

from sqlalchemy.schema import SchemaItem

from app.models import SCHEMA


def include_object(
    obj: SchemaItem,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: SchemaItem | None,
) -> bool:
    """Whether autogenerate may consider one reflected or declared object.

    `include_schemas=True` is required for alembic to see `admin` at all, but it also makes
    alembic reflect every other schema in the database — `public` included. Without this filter
    the first autogenerated revision would helpfully propose dropping whatever else lives there.

    The comparison is against `admin`, and it is written that way round on purpose. Alembic and
    SQLAlchemy both name the default schema `None`, never the string "public", so a predicate
    that excluded objects whose schema is "public" would match nothing and let every one of them
    through. Naming the schema that is wanted is the version of this that cannot be inert: every
    table in this application's metadata carries `schema="admin"`, and everything else — reflected
    out of public, or out of a schema some other service owns — does not.
    """
    schema = getattr(obj, "schema", None)
    if schema is None:
        # Columns, indexes and constraints have no schema of their own; they belong to the one
        # their table is in.
        schema = getattr(getattr(obj, "table", None), "schema", None)
    return schema == SCHEMA
