"""Every Tailwind utility written in the frontend's markup, and whether it produced any CSS.

WHY THIS EXISTS. The theme in `frontend/src/styles/tokens.css` closes Tailwind's namespaces —
`--color-*: initial`, `--radius-*: initial`, `--spacing-*: initial` and the rest — so the only
values available are the ones docs/design.md describes. That is the point, and it has one failure
mode: a utility asking for a step this project does not define compiles to *nothing at all*. No
warning, no error, no rule in the output. The element renders with square corners, or with no
height, or at its content width, and the source looks correct.

Three real defects so far, each found by looking at a screen rather than by any check:

    rounded-2xl   a generated card, drawn with square corners
    h-9           a select trigger twenty pixels tall, because there is no --spacing-9
    w-56          the same trigger at content width, because there is no --spacing-56

All three arrived the same way: a component generated by `shadcn-vue add`, written against
Tailwind's stock scale, dropped into a project whose scale is deliberately smaller.

WHY IT PARSES RATHER THAN GREPS. The first version of this was a grep over the source text, and it
reported `left-aligned` and `top-level` out of English sentences in comments and `text-right` out
of a regular expression in a test. A check with three false alarms out of six is a check somebody
turns off. So this reads the places a class name can actually be: `class` and `:class` attributes,
and the string arguments of `cn(...)`, with comments removed first.

Run through ./scripts/check-design.sh, which owns the build it reads.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "frontend" / "src"

# Only the namespaces this project closes. The rest of Tailwind is open, its defaults apply, and a
# utility from it compiles whether or not anybody thought about the value.
CLOSED = (
    "rounded",
    "text",
    "h",
    "w",
    "size",
    "min-w",
    "max-w",
    "min-h",
    "max-h",
    "gap",
    "gap-x",
    "gap-y",
    "p",
    "px",
    "py",
    "pt",
    "pb",
    "pl",
    "pr",
    "m",
    "mx",
    "my",
    "mt",
    "mb",
    "ml",
    "mr",
    "space-x",
    "space-y",
    "translate-x",
    "translate-y",
)

_COMMENTS = (
    re.compile(r"<!--.*?-->", re.S),
    re.compile(r"/\*.*?\*/", re.S),
    re.compile(r"(?<![:\w])//[^\n]*"),
)

# `class="..."` and `:class="..."`, plus every string and template literal — a class list reaches
# an element through `cn(...)`, through a `const` and through a ternary, and trying to follow which
# is how a scanner starts missing things. The closed-namespace filter below is what keeps ordinary
# prose in a string from being mistaken for a utility.
_ATTRIBUTES = re.compile(r""":?class\s*=\s*(?P<q>["'])(?P<body>.*?)(?P=q)""", re.S)
_LITERAL = re.compile(r"""(['"`])(?P<body>(?:\\.|(?!\1).)*)\1""", re.S)

# LITERALS ARE READ FROM THE SCRIPT ONLY, AND THE REASON IS AN APOSTROPHE.
#
# A template is not TypeScript, and its text is prose. One `service's` in a paragraph opens a
# string literal that runs to the next apostrophe anywhere in the file, swallowing every quote in
# between — so `class="… p-4"` two elements later is read as starting at the wrong quote, and the
# scanner reports `p-4">` and eight of its neighbours as utilities that compile to nothing.
#
# Found by writing that paragraph. The failure is loud rather than silent, but it names nine
# utilities that are all fine and hides the one that is not, which is a check people learn to
# ignore. Attributes are still read from the whole file; only the literal sweep is narrowed.
_SCRIPT = re.compile(r"<script\b[^>]*>(?P<body>.*?)</script>", re.S)

# What a token can be wrapped in when a regex tears it out of source: the quote that ended its
# literal, the comma after it, a stray brace from an interpolation.
_EDGES = "'\"`,;{}"


def _without_comments(text: str) -> str:
    for pattern in _COMMENTS:
        text = pattern.sub(" ", text)
    return text


def _candidates(text: str, *, single_file_unit: bool) -> set[str]:
    """Every whitespace-separated token that could be a class name in this file.

    `single_file_unit` is true for a `.vue` file, where the template is markup and only the
    `<script>` blocks are TypeScript.
    """
    found: set[str] = set()
    body = _without_comments(text)
    for match in _ATTRIBUTES.finditer(body):
        found.update(match.group("body").split())
    scripts = (
        [block.group("body") for block in _SCRIPT.finditer(body)] if single_file_unit else [body]
    )
    for script in scripts:
        for literal in _LITERAL.finditer(script):
            found.update(literal.group("body").split())
    return {token for token in (raw.strip(_EDGES) for raw in found) if token}


def _base(candidate: str) -> str:
    """The utility itself, with its variants and its negation removed.

    `dark:hover:h-9` is `h-9`; `data-[state=open]:rounded-md` is `rounded-md`. Bracketed
    conditions can contain colons of their own, so the split walks from the right and stops at the
    first colon that is not inside brackets.
    """
    depth = 0
    for index in range(len(candidate) - 1, -1, -1):
        character = candidate[index]
        if character == "]":
            depth += 1
        elif character == "[":
            depth -= 1
        elif character == ":" and depth == 0:
            return candidate[index + 1 :].lstrip("-")
    return candidate.lstrip("-")


def _is_closed_namespace(utility: str) -> bool:
    if "[" in utility or "(" in utility:
        # An arbitrary value — `w-[13px]` — or a variable reference — `max-h-(--reka-height)` —
        # carries its own value and always compiles. Whether that value is one docs/design.md
        # agreed to is a different question, and the palette check is where it lives.
        return False
    for prefix in CLOSED:
        if utility.startswith(prefix + "-") and utility != prefix + "-":
            return True
    return False


def main(argv: list[str]) -> int:
    if not argv:
        print("usage: utilities.py <built.css>", file=sys.stderr)
        return 2
    # Backslashes removed before the search. A selector escapes the characters that are not valid
    # in a CSS identifier — `.w-1\/2`, `.max-w-\[13px\]` — so `w-1/2` is not a substring of the
    # stylesheet that contains it, and looking for it naively reports a utility that compiled fine.
    css = Path(argv[0]).read_text(encoding="utf-8").replace("\\", "")

    missing: dict[str, set[str]] = {}
    for path in sorted(SOURCE.rglob("*")):
        if path.suffix not in {".vue", ".ts"} or path.name.endswith(".spec.ts"):
            continue
        for candidate in _candidates(
            path.read_text(encoding="utf-8"), single_file_unit=path.suffix == ".vue"
        ):
            utility = _base(candidate)
            if not _is_closed_namespace(utility):
                continue
            if utility not in css:
                missing.setdefault(utility, set()).add(str(path.relative_to(ROOT)))

    for utility, files in sorted(missing.items()):
        where = ", ".join(sorted(files))
        print(
            f"::error file={where.split(',')[0]}::{utility} compiles to nothing; it asks for a "
            f"step the closed namespaces do not define. Used in: {where}"
        )
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
