import type { ClassValue } from 'clsx'
import { clsx } from 'clsx'
import { extendTailwindMerge } from 'tailwind-merge'

/**
 * `tailwind-merge`, taught this project's scales.
 *
 * WHY IT HAS TO BE TAUGHT. Its whole job is to resolve conflicts — given `p-2 p-4` it keeps the
 * last — and it decides what conflicts by pattern-matching Tailwind's stock class names. This
 * project's theme replaces those, so `text-caption` is a size it has never heard of. It reads the
 * prefix, files it under text colour, and when the same string carries a colour as well it keeps
 * the colour and drops the size.
 *
 * That is not theoretical. `text-caption text-text-primary` on the tooltip resolved to
 * `text-text-primary`, and the panel rendered at the inherited size with the source reading
 * correctly — the class is written, it compiles, and it is removed at runtime by the helper that
 * exists to keep class lists tidy. `scripts/utilities.py` cannot see this one: the utility does
 * produce CSS, it simply never reaches the element.
 *
 * So the two namespaces where a name of ours can collide with a name of theirs are declared. Only
 * `cn()` is affected — a plain `class="text-ui text-text-primary"` in a template never goes
 * through here — which is why this surfaced in a component generated by `shadcn-vue` rather than
 * in one written by hand.
 */
const twMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      // The five sizes from docs/design.md. Without this every one of them loses to a colour.
      'font-size': [{ text: ['caption', 'dense', 'ui', 'heading', 'title'] }],
      // The four radii. This direction is the opposite failure: unknown to it, `rounded-control`
      // and `rounded-panel` did not conflict, so both survived and the cascade picked the winner.
      rounded: [{ rounded: ['control', 'panel', 'card', 'chip'] }],
    },
  },
})

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
